;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-kill-line
        cua-paste
        dashboard-next-line
        dashboard-return
        elscreen-next
        helm-M-x
        indent-for-tab-command
        markdown-enter-key
        markdown-outdent-or-delete
        my-completion
        seq-end
        swiper
        undefined
        yaml-electric-backspace
        yaml-electric-bar-and-angle
        ))

(setq mc/cmds-to-run-once
      '(
        electric-pair-delete-pair
        end-of-buffer
        helm-show-kill-ring
        seq-begin
        yaml-electric-dash-and-dot
        ))
