;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-kill-line
        cua-cut-region
        cua-paste
        elscreen-next
        helm-M-x
        indent-for-tab-command
        markdown-enter-key
        markdown-outdent-or-delete
        my-completion
        seq-cua
        swiper
        undefined
        undo-tree-visualize
        yaml-electric-backspace
        yaml-electric-bar-and-angle
        ))

(setq mc/cmds-to-run-once
      '(
        end-of-buffer
        seq-begin
        yaml-electric-dash-and-dot
        ))
